['hsa-mir-1321', 'ADIPOQ', 'CRBN', 'SNORD109B', 'LOC145783', 'JRKL', 'MUC2', 'MUC1', 'MUC7', 'MUC6', 'CRB3', 'MUC4', 'FAM205B', 'LOC100128750', 'FAM205A', 'LOC375010', 'LOC441666', 'NRTN', 'TSG101', 'LOC440131', 'ORAI1', 'hsa-mir-552', 'FLJ33630', 'DNASE1L2', 'DNASE1L3', 'ZEB1', 'ZEB2', 'KRTAP10-9', 'CD40LG', 'XAGE2B', 'LOC100505841', 'ATE1', 'AIG1', 'ZNF890P', 'ENOPH1', 'ERVK13-1', 'ADARB2', 'ADARB1', 'CXXC1', 'CXXC5', 'CXXC4', 'WTIP', 'CTHRC1', 'MAGEA9', 'MAGEA8', 'MAGEA3', 'MAGEA2']
Traceback (most recent call last):
  File "coversizetestall.py", line 151, in <module>
    coverarr = dict[str(k2) + "_" + str(k1)]
KeyError: '1_1'
