['LINC00221', 'LINC00222', 'LOC441461', 'PTGDR', 'PTGDS', 'TBC1D23', 'TBC1D21', 'TBC1D20', 'TBC1D26', 'TBC1D25', 'ARPC2', 'TBC1D29', 'TBC1D28', 'C20orf152', 'C20orf151', 'FUNDC2', 'TBC1D2B', 'MT1JP', 'ARPC4', 'TYRO3', 'POC1A', 'ZNF354C', 'TMPRSS13', 'ZNF354B', 'WDFY4', 'WDFY3', 'WDFY2', 'WDFY1', 'FLJ21408', 'WDR83OS', 'TPI1P2', 'TPI1P3', 'TFAMP1', 'ANKRD35', 'ANKRD36', 'ANKRD37', 'ANKRD31', 'ANKRD32', 'ANKRD33', 'ANKRD39', 'PRAME', 'FAM194A', 'FAM194B', 'MECR', 'MIR99B', 'SNORA80', 'RCAN3AS']
Traceback (most recent call last):
  File "coversizetestall.py", line 151, in <module>
    coverarr = dict[str(k2) + "_" + str(k1)]
KeyError: '1_1'
